import type { Metadata } from "next";
import "./globals.css";

import Navbar from "../components/Navbar";
import TopNavbar from "../components/TopNavbar";

export const metadata: Metadata = {
  title: "Chatter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <div className="flex place-items-center px-6 h-[80px] bg-neutral-900">
          <TopNavbar />
        </div>
        <div className="flex ">
          <div className="min-w-[220px] hidden md:block px-6 bg-neutral-900 h-screen">
            <Navbar />
          </div>
          <div className="mx-auto my-8 w-11/12 md:w-[800px] p-8 h-[90vh] overflow-auto invisible-scrollbar">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
