import type { Metadata } from "next";
import "./globals.css";

import Navbar from "../components/Navbar";
import TopNavbar from "../components/TopNavbar";
import AuthProvider from "@/components/AuthProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata: Metadata = {
  title: "Chatter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="overflow-hidden">
          <TopNavbar />
          <div className="flex flex-col-reverse place-content-between justify-between md:flex-row">
            <Navbar />
            <div className="mx-auto my-8 w-11/12 md:w-[800px] md:p-8 h-[90vh] overflow-auto invisible-scrollbar">
              {children}
              <ToastContainer />
            </div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
